name: mexanyd_desktop
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1-alpha.1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  printing: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true
