name: mexanyd_desktop
description: "A tool created to help with tasks from an auto parts store."
publish_to: "none"
version: 0.0.1-alpha.1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  printing: ^5.12.0
  path: ^1.9.0
  path_provider: ^2.1.3
  sqflite_common_ffi: ^2.3.3
  window_manager: ^0.3.8
  shared_preferences: ^2.2.3
  pdf: ^3.10.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
